### ISSUE TITLE
need apk

### ISSUE THREAD

**Issue by ghost** [Yash-Garg/qBittorrent-KT#128]
here please:
https://github.com/Yash-Garg/qBittorrent-KT/releases

**Comment by Yash-Garg** [comment]
> here please: https://github.com/Yash-Garg/qBittorrent-KT/releases

It's not yet complete that's why I have not published any releases yet.

However, I can maybe setup a GitHub Action to publish snapshots of the commits pushed on `develop` branch.

**Comment by yash-garg** [comment]
> here please: https://github.com/Yash-Garg/qBittorrent-KT/releases

It's not yet complete that's why I have not published any releases yet.

I'll start publishing the alpha builds on play store and share the link here soon.

**Comment by yash-garg** [comment]
It's published on play store you can find it here https://play.google.com/store/apps/details?id=dev.yashgarg.qbit
