### ISSUE TITLE
[BUG] App doesn't redirect to `ServerFragment` after adding `ServerConfig`

### ISSUE THREAD

**Issue by exolon** [Yash-Garg/qBittorrent-KT#179]
A13 here.

Adding a server, testing goes ok, app toast says server was added, but page remains blank and cannot continue.

**Comment by yash-garg** [comment]
> A13 here.
> 
> Adding a server, testing goes ok, app toast says server was added, but page remains blank and cannot continue.

Thanks for the report, I'll have a look at it once on A13.

**Comment by exolon** [comment]
> > A13 here.
> > Adding a server, testing goes ok, app toast says server was added, but page remains blank and cannot continue.
> 
> Thanks for the report, I'll have a look at it once on A13.

Let me know if you'd like me to debug it somehow for you!

**Comment by Yash-Garg** [comment]
> 

Can you check logs if there's anything related to the application? Thanks!

**Comment by yash-garg** [comment]
> > > A13 here.
> > > Adding a server, testing goes ok, app toast says server was added, but page remains blank and cannot continue.
> > 
> > 
> > Thanks for the report, I'll have a look at it once on A13.
> 
> Let me know if you'd like me to debug it somehow for you!


Can you check logs if there's anything related to the application? Thanks!

**Comment by exolon** [comment]
> Can you check logs if there's anything related to the application? Thanks!

Logcat?

**Comment by yash-garg** [comment]
> > Can you check logs if there's anything related to the application? Thanks!
> 
> Logcat?

Yes

**Comment by exolon** [comment]
Ran a cycle and after adding the server this is what I got: hmmm formatting fails, sorry)

`<<< log_count = 10 >>>
[11-26 17:31:01.899 1679:3947 D/CoreBackPreview]
Window{efd6fa8 u0 dev.yashgarg.qbit/dev.yashgarg.qbit.MainActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@ffd5e2a, mPriority=0}

[11-26 17:31:01.981 12922:12922 I/GoogleInputMethodService]
GoogleInputMethodService.onStartInput():1877 onStartInput(EditorInfo{inputType=0x81(Password) imeOptions=0x4000006 privateImeOptions=null actionName=DONE actionLabel=null actionId=0 initialSelStart=6 initialSelEnd=6 initialCapsMode=0x0 hintText=non-empty label=null packageName=dev.yashgarg.qbit fieldId=2131296703 fieldName=null extras=Bundle[mParcelledData.dataSize=240]}, false)

[11-26 17:31:01.985 12922:12922 I/GoogleInputMethodService]
GoogleInputMethodService.onStartInputView():1995 onStartInputView(EditorInfo{inputType=0x81(Password) imeOptions=0x4000006 privateImeOptions=null actionName=DONE actionLabel=null actionId=0 initialSelStart=6 initialSelEnd=6 initialCapsMode=0x0 hintText=non-empty label=null packageName=dev.yashgarg.qbit fieldId=2131296703 fieldName=null extras=Bundle[{android.support.text.emoji.emojiCompat_metadataVersion=8, android.support.text.emoji.emojiCompat_replaceAll=false}]}, false)

[11-26 17:31:01.990 12922:12922 I/AndroidIME]
AbstractIme.onActivate():86 PasswordIme.onActivate() : EditorInfo = inputType=0x81(Password) imeOptions=0x4000006 privateImeOptions=null actionName=DONE actionLabel=null actionId=0 initialSelStart=6 initialSelEnd=6 initialCapsMode=0x0 hintText=non-empty label=null packageName=dev.yashgarg.qbit fieldId=2131296703 fieldName=null extras=Bundle[{android.support.text.emoji.emojiCompat_metadataVersion=8, android.support.text.emoji.emojiCompat_replaceAll=false}], IncognitoMode = false, DeviceLocked = false

[11-26 17:31:02.005 1679:2726 D/CoreBackPreview]
Window{efd6fa8 u0 dev.yashgarg.qbit/dev.yashgarg.qbit.MainActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@7feb12c, mPriority=0}

[11-26 17:31:02.389 1679:3951 D/CoreBackPreview]
Window{efd6fa8 u0 dev.yashgarg.qbit/dev.yashgarg.qbit.MainActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@78b78de, mPriority=0}

[11-26 17:31:02.431 12922:12922 I/GoogleInputMethodService]
GoogleInputMethodService.onStartInput():1877 onStartInput(EditorInfo{inputType=0x81(Password) imeOptions=0x4000006 privateImeOptions=null actionName=DONE actionLabel=null actionId=0 initialSelStart=6 initialSelEnd=6 initialCapsMode=0x0 hintText=non-empty label=null packageName=dev.yashgarg.qbit fieldId=2131296703 fieldName=null extras=Bundle[mParcelledData.dataSize=240]}, true)

[11-26 17:31:02.440 1679:5345 D/CoreBackPreview]
Window{efd6fa8 u0 dev.yashgarg.qbit/dev.yashgarg.qbit.MainActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@7a31e78, mPriority=-1}

[11-26 17:31:03.839 1679:3951 I/InputDispatcher]
Channel [Gesture Monitor] swipe-up (server) is stealing touch from [efd6fa8 dev.yashgarg.qbit/dev.yashgarg.qbit.MainActivity (server), [Gesture Monitor] edge-swipe (server)]

[11-26 17:31:06.457 1679:2342 W/NotificationService]
Toast already killed. pkg=dev.yashgarg.qbit token=android.os.BinderProxy@a61346e

`

**Comment by yash-garg** [comment]
@exolon thanks for the log but I don't see anything here.

Also it's kind of a weird issue, because I tried on my Physical Android 13 device and it works there. 
But doesn't work on Emulator when I tried, will need to look more into it.


https://user-images.githubusercontent.com/33605526/204097558-688afbb4-b4be-4046-8ba5-f2584100bda7.mp4

**Comment by exolon** [comment]
Yeah that's the behavior I'm getting. Weird! I thought the log was clear, too. What's the config path under root? Maybe I could add the server manually?

**Comment by yash-garg** [comment]
> Yeah that's the behavior I'm getting. Weird! I thought the log was clear, too. What's the config path under root? Maybe I could add the server manually?

Can't be done like that as it is handled by a database managed by the application, I'll try to figure it out and let you know!

**Comment by yash-garg** [comment]
@exolon I've figured out the issue, will publish a new build on play store soon!

**Comment by exolon** [comment]
> @exolon I've figured out the issue, will publish a new build on play store soon!

Great! Will keep an eye out for it and report back!

**Comment by yash-garg** [comment]
> > @exolon I've figured out the issue, will publish a new build on play store soon!
> 
> Great! Will keep an eye out for it and report back! 

Update should be up on play store.

**Comment by exolon** [comment]
> > > @exolon I've figured out the issue, will publish a new build on play store soon!
> > 
> > 
> > Great! Will keep an eye out for it and report back!
> 
> Update should be up on play store.

Yessss it works, thanks!
