### ISSUE TITLE
allow self signed certificates

### ISSUE THREAD

**Issue by mariorossi77** [Yash-Garg/qBittorrent-KT#188]
for https selfhosted servers in lan environments theres no need for a trusted ca.

**Comment by yash-garg** [comment]
Please try to follow the [template](https://github.com/Yash-Garg/qBittorrent-Manager/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=%5BFEATURE+REQUEST%5D). 

Regarding the issues, I tried to implement this earlier but got some blockers will need to look more into it when I'll get time.
