### ISSUE TITLE
[BUG] Wrong port when testing server connection

### ISSUE THREAD

**Issue by mariorossi77** [Yash-Garg/qBittorrent-KT#189]
client connects to the server on the wrong port

when configuring the server, after specifying "HTTP" and port "443" 
the client connects to port 80

the client should connect to port 443 even if the standard http port is 80

**Comment by Yash-Garg** [comment]
@kusky3 can you follow the [Bug Report](https://github.com/Yash-Garg/qBittorrent-Manager/issues/new?assignees=&labels=bug&template=bug_report.md&title=%5BBUG%5D) template please?

**Comment by yash-garg** [comment]
@kusky3 can you follow the [Bug Report](https://github.com/Yash-Garg/qBittorrent-Manager/issues/new?assignees=&labels=bug&template=bug_report.md&title=%5BBUG%5D) template please? I'll have a look at the issue.

**Comment by Yash-Garg** [comment]
So this issue is only happening with ports `80` and `443`, will need to look more on it and how can I proceed with the fix. Maybe I can add a toggle to not specify a port completely for them?

**Comment by yash-garg** [comment]
@kusky3 I've implemented a solution by making `port` optional, so if you are using any kind of proxy which handles the port forwarding, leaving the port as empty should work just fine now.

Will create a release after the PR has been merged.
