### ISSUE TITLE
[FEATURE REQUEST] Implement connecting to subdirectories

### ISSUE THREAD

**Issue by glodomorrapl** [Yash-Garg/qBittorrent-KT#193]
**Is your feature request related to a problem? Please describe.**
yes, because this app does not let you specify the subdirectory to which the app should connect to. if your qbittorrent instance is exposed through a subdirectory (eg. https://my.home.server/qbittorrent), the app will not be able to connect 

**Describe the solution you'd like**
implement a feature to allow the user to do exactly that. 

**Describe alternatives you've considered**
using other apps I guess? 

**Additional context**
screenshot from another app that implements this feature:
![Screenshot_20221207-114605-954](https://user-images.githubusercontent.com/74612187/206158824-144bd3b4-76aa-4f94-917a-f050f745b78d.png)

**Comment by yash-garg** [comment]
@glodomorrapl Thanks for creating the issue! Will definitely try to implement this in upcoming releases.

**Comment by yash-garg** [comment]
Hey @glodomorrapl, I've implemented the feature but I can't test it as I don't have a proxy set up that way. Can you test with the Debug APK I'm attaching below and let me know? Thanks!

[Debug APK.zip](https://github.com/Yash-Garg/qBittorrent-Manager/files/10177645/Debug.APKs.zip)

**Comment by glodomorrapl** [comment]
![Screenshot_20221207-203935-367](https://user-images.githubusercontent.com/74612187/206279400-3d4e87e3-560d-4daa-8c19-1a29b7a696bb.png)

unfortunately something didn't quite work, the test goes through but I'm getting this error. it also softlocks the app, I can't do anything but clear app data and try adding the server again

**Comment by Yash-Garg** [comment]
> 
> ![Screenshot_20221207-203935-367](https://user-images.githubusercontent.com/74612187/206279400-3d4e87e3-560d-4daa-8c19-1a29b7a696bb.png)
> 
> unfortunately something didn't quite work, the test goes through but I'm getting this error. it also softlocks the app, I can't do anything but clear app data and try adding the server again

Weird, I'll take a look again why it's happening.

**Comment by yash-garg** [comment]
Okay, I think I found the issue. Will try the fix and give a new APK, thanks for testing!

**Comment by yash-garg** [comment]
Hey @glodomorrapl, checkout with the new APK mentioned below. It should work fine now hopefully.

[Debug APKs.zip](https://github.com/Yash-Garg/qBittorrent-Manager/files/10181759/Debug.APKs.zip)

**Comment by glodomorrapl** [comment]
![Screenshot_20221208-071655-400](https://user-images.githubusercontent.com/74612187/206372153-7a08bdbf-0cf0-4902-bdb1-619aa26bc614.png)
nice, seems to be working now :) checked torrent properties, all seems to be here, but the category and sort buttons on the torrent list don't seem to work, nothing happens when I press them.

**Comment by yash-garg** [comment]
@glodomorrapl yes those are not yet implemented https://github.com/Yash-Garg/qBittorrent-Manager/issues/142, I am not getting much time due to IRL stuff to work more on this. I plan to add support for all the features gradually before [v1.0](https://github.com/Yash-Garg/qBittorrent-Manager/milestone/1) release.
