### ISSUE TITLE
[BUG] After upgrading to 0.1.8fce71 I get "403 forbidden"

### ISSUE THREAD

**Issue by 825i** [Yash-Garg/qBittorrent-KT#203]
After updating to the version released today, I got 403 forbidden when opening the app.

I had to clear all data and cache in order to even use it and relogin because there is no way to access the settings without doing that.

Nothing in my app config changed at all. So the app really should have worked fine after updating.

**Comment by Yash-Garg** [comment]
Weird, that should not have happened. @825i from what versions did you upgrade to `v0.1.8`?

**Comment by yash-garg** [comment]
Thanks for the bug report @825i. Sorry for the inconvenience caused!

I've applied a fix for proper migration, please let me know if you face the same issue on the next release.
