### ISSUE TITLE
[BUG] Failed! z9.a error in 0.2.0

### ISSUE THREAD

**Issue by AmaryllisVFX** [Yash-Garg/qBittorrent-KT#283]
**Describe the bug**
After updating the app to v0.2.0, opening the app results in a "Failed! z9.a" error and the torrents don't load. Clearing app data and re adding the server also produces the same error and the server can't be added. This bug is not present in the previous version.

**To Reproduce**
1. Add a server
2. Enter details
3. Press Save and test config

**Expected behavior**
The app loads the torrents correctly as in previous versions.

**Smartphone (please complete the following information):**
 - Device: POCO F1
 - OS: Android 13
 - App Version V0.2.0

**Additional context**

**Comment by Yash-Garg** [comment]
@AmaryllisVFX What is the qBittorrrent version?

**Comment by yash-garg** [comment]
Thanks for the report @AmaryllisVFX!

Fixed the issue in https://github.com/Yash-Garg/qBittorrent-Manager/commit/f4c4e0b7aa10708896814272bf2c51c4ef94c6f9, please try the [v0.2.1](https://yashgarg.dev/g/qbittorrent-manager/releases/latest) APK.

**Comment by AmaryllisVFX** [comment]
Great! The new version successfully fixed the issue for me. Thanks for the quick reply and fix!
